substitutions:
  dallas_address: "0xd63ce10457487528"

esphome:
  name: fan-victron-orion-dc-charger
  friendly_name: Cooling Fan for Victron Orion DC Charger

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: ERROR
  logs:
    dallas.sensor: none
    number: none
    sensor: none
    light: none
    fan: none

# Enable Home Assistant API
api:
  encryption:
    key: "pD5POkoUsLKZhs7/l82lh75II3wDsQoCku6tOaoyf/U="

ota:
  - platform: esphome
    password: "dc069ead6a1cfadd028cb54c7418c0a7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fan-Victron-Orion-Dc-Charger"
    password: "cVZ8rJwFDoWT"

captive_portal:

number:
  # Slider to set Min Temperature to start fan
  - platform: template
    id: fan_threshold
    name: Threshold Temperature
    optimistic: True
    min_value: 20
    max_value: 60
    initial_value: 25
    step: 1
    restore_value: true # Store setting between reboots

  # # Home Assistant Slider for Temperature Update Interval
  # - platform: homeassistant
  #   entity_id: input_number.temperature_update_interval
  #   id: update_interval
  #   internal: true  # Not exposed as a sensor in ESPHome


# DS18B20 Temperature Sensor
one_wire:
  - platform: gpio
    # pin: D7
    pin: GPIO13

sensor:
  # Fan Speed Sensor (Reports % Speed to Home Assistant)
  - platform: template
    name: "Fan Speed"
    id: fan_speed_sensor
    unit_of_measurement: "%"
    accuracy_decimals: 0
    
  # Update Interval (Reports interval to Home Assistant)
  - platform: template
    name: "Update Interval"
    id: update_interval
    unit_of_measurement: "s"
    accuracy_decimals: 0
    
  # DHT11 Ambient Temperature Sensor
  - platform: dht
    pin: D5  # GPIO14
    model: DHT11
    temperature:
      name: "Ambient Temperature"
      id: ambient_temp
    humidity:
      name: "Ambient Humidity"
      id: ambient_humidity
    update_interval: 5s

  # Dallas DS18B20 Victron Orion DC Charger Temperature Sensor
  - platform: dallas_temp
    address: $dallas_address
    name: "Victron Charger Temp"
    id: charger_temp
    update_interval: 5s

    # Adjust fan speed(1-100%). Else, turn it off and set the speed to 1
    on_value:
      - lambda: !lambda |
          float temp = id(charger_temp).state;
          float threshold = id(fan_threshold).state;
          float speed = 0.0;

          if (temp >= threshold) {
            speed = (temp - threshold) / 10.0;  // Scale speed from 0 to 1
            if (speed > 1.0) speed = 1.0;
          }

          id(fan_pwm_output).set_level(speed);
          id(fan_speed_sensor).publish_state(speed * 100.0);  // Convert to percentage and publish
          id(charger_temp).set_update_interval(100000);

# PWM Control via MOSFET
output:
  - platform: esp8266_pwm
    pin: D2  # GPIO4 (MOSFET Gate)
    frequency: 20kHz # 20kHz should be outside hearing range
    id: fan_pwm_output

# Fan Speed Automation (Dynamic Speed Based on Temperature)
fan:
  - platform: speed
    output: fan_pwm_output
    name: "Cooling Fan"
    id: cooling_fan



